name: PHP Insights
on:
  - pull_request

jobs:
  phpinsights:
    runs-on: ubuntu-latest
    name: PHP Insights checks
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
      - run: composer install -q --no-ansi --no-interaction --no-progress --prefer-dist
      - run: vendor/bin/phpinsights -n --ansi --format=github-action
