name: PHP Type Coverage
on:
  - pull_request

jobs:
  phpinsights:
    runs-on: ubuntu-latest
    name: PHP Type Coverage
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
      - run: composer install -q --no-ansi --no-interaction --no-progress --prefer-dist
      - run: php artisan test --type-coverage --min=90
